name: Start MySQL
steps:
- uses: samin/mysql-action@v1
  with:
    host port: 3800 # Optional, default value is 3306. The port of host
    container port: 3307 # Optional, default value is 3306. The port of container

